### ISSUE TITLE
ansible version in README

### ISSUE THREAD

**Issue by pwalczysko** [ome/omero-deployment-examples#69]
Is the version specified in README not outdated ?

Issues encountered:

1. The version of Ansible in https://github.com/ome/omero-deployment-examples#readme does not work as written on MacOS, ``pip install ansible>=2.6.16,<2.7`` is not interpreted correctly by bash I guess
2. When replacing the ``pip install ansible>=2.6.16,<2.7`` with ``pip install ansible==2.6.16``, I am hitting 
```
(testan) pwalczysko@ls31618~/Work/omero-deployment-examples/ansible-example-omero-onenode$ ansible --version
ansible 2.6.16
  config file = None
  configured module search path = ['/Users/pwalczysko/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/pwalczysko/opt/anaconda3/envs/testan/lib/python3.8/site-packages/ansible
  executable location = /Users/pwalczysko/opt/anaconda3/envs/testan/bin/ansible
  python version = 3.8.13 (default, Mar 28 2022, 06:16:26) [Clang 12.0.0 ]
(testan) pwalczysko@ls31618~/Work/omero-deployment-examples/ansible-example-omero-onenode$ ansible-playbook playbook.yml
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note
that the implicit localhost does not match 'all'


PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ERROR! Unexpected Exception, this is probably a bug: cannot pickle '_io.TextIOWrapper' object
```

3. What works for me is ``pip install ansible==2.8.18`` (the same version I use for the day-to-day ansible work, with python 3.7.6 (in conda env).

Should we maybe see if we can update the version here, @sbesson ? What is your ansible setup please ?

FYI: This is in prep for a new omero-guide, see https://github.com/ome/omero-guides/compare/master...pwalczysko:omero-guides:install-omero

**Comment by sbesson** [comment]
> If we could just move to "pip install ansible" again it would be easier for upkeep. Or may with additional ("at time of writing 2.8")

:+1: for being able to upgrade to upstream Ansible eventually. To communicate the fact we are using an older version without needing to track & update versions, I have been lately referring to the version of Ansible installed by the [ome-ansible-molecule](https://pypi.org/project/ome-ansible-molecule/) meta-package as the stable version used by the OME team.

**Comment by pwalczysko** [comment]
Fix suggested in https://github.com/ome/omero-deployment-examples/pull/70

**Comment by pwalczysko** [comment]
In the testing captured in https://github.com/ome/ansible-example-omero-onenode/pull/11#issuecomment-1211908122 the ansible version did not seem to be a problem. It was rather the combination of python 3.6 or 3.8 and ansible versions which were causing some back and forth (latest ansible does not support python 3.6, but OMERO will not successfully install on CentOS 7 with python 3.8 (ice problem reported)).

**Comment by joshmoore** [comment]
@pwalczysko : can this be closed?

**Comment by pwalczysko** [comment]
yes, thank you
